apiVersion: v1
kind: Service
metadata:
  name: executor-service
  namespace: task-orchestrator
  labels:
    app.kubernetes.io/name: executor-service
    app.kubernetes.io/component: executor-service
    app.kubernetes.io/part-of: task-orchestrator-engine
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: executor-service
  ports:
    - name: http
      port: 5001
      targetPort: 5001
      protocol: TCP
