apiVersion: v1
kind: Service
metadata:
  name: scheduler-api
  namespace: task-orchestrator
  labels:
    app.kubernetes.io/name: scheduler-api
    app.kubernetes.io/component: scheduler-api
    app.kubernetes.io/part-of: task-orchestrator-engine
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: scheduler-api
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
