apiVersion: v1
kind: Service
metadata:
  name: monitor-service
  namespace: task-orchestrator
  labels:
    app.kubernetes.io/name: monitor-service
    app.kubernetes.io/component: monitor-service
    app.kubernetes.io/part-of: task-orchestrator-engine
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: monitor-service
  ports:
    - name: http
      port: 5003
      targetPort: 5003
      protocol: TCP
